services:
  _defaults:
    public: true

  expressopinionlite.repository.question_repository:
    class: 'Ericc70\Expressopinionlite\Repository\QuestionRepository'
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments: 
      - Ericc70\Expressopinionlite\Entity\EcExpressopinionsliteQuestion
 
  expressopinionlite.repository.response_repository:
    class: 'Ericc70\Expressopinionlite\Repository\ResponseRepository'
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments: 
      - Ericc70\Expressopinionlite\Entity\EcExpressopinionsliteResponse

  expressopinionlite.repository.vote_repository:
    class: 'Ericc70\Expressopinionlite\Repository\VoteRepository'
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments: 
      - Ericc70\Expressopinionlite\Entity\EcExpressopinionsliteVote
  
  expressopinionlite.repository.vote_history_repository:
    class: 'Ericc70\Expressopinionlite\Repository\VoteHistoryRepository'
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments: 
      - Ericc70\Expressopinionlite\Entity\EcExpressopinionsliteVoteHistory
