ec_expressOpinion_index:
  path: /
  methods: GET
  defaults:
    _controller: Ericc70\Expressopinionlite\Controller\AdminExpressOpinionLite::indexAction
    _disable_module_prefix: true
    _legacy_controller: AdminExpressOpinionLite
    _legacy_link: AdminExpressOpinionLite


ec_expressOpinion_question:
  path: /question
  methods: [GET, POST]
  defaults:
    _controller: Ericc70\Expressopinionlite\Controller\AdminQuestionController::indexAction
    _disable_module_prefix: true
    _legacy_controller: AdminQuestionController
    _legacy_link: AdminQuestionController


ec_expressOpinion_ajax_update_reponse:
  path: /response/a/edit
  methods: [PUT, POST]
  defaults:
    _controller: Ericc70\Expressopinionlite\Controller\AdminResponseController::updateByAjax
    _disable_module_prefix: true
    _legacy_controller: AdminResponseController
    _legacy_link: AdminResponseController